import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/Provider/themeProvider";
import { Toaster } from "sonner";
import TanstackQueryProvider from "@/components/Provider/tanstackQueryProvider";



const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-montserrat",
  display: "swap",
});
export const metadata: Metadata = {
  title: "SkillBridge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body
        className={`${montserrat.variable} font-sans `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TanstackQueryProvider>
      
              {children}
      
            <Toaster richColors={true} />
          </TanstackQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
